version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./deployments/docker/Dockerfile
    container_name: wallet-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - config.env
    network_mode: host

  postgres:
    image: postgres:14-alpine
    container_name: wallet-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-wallet_db}
    ports:
      - "5435:5431"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres-data:
